import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Jhon",
      email: "jhon@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Thom",
      email: "thom@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      type: "Memory Ram Corsair RGB Pro ",
      category: "pc components",
      image: "/images/ram1.jpg",
      capacity: "8GB",
      brand: "Corsair",
      price: 172.99,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      type: "Memory Ram PNY XLR8",
      category: "pc components",
      image: "/images/ram2.jpg",
      capacity: "8GB",
      brand: "PNY",
      price: 84.99,
      countInStock: 5,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      type: "Memory Ram Corsair Vengeance",
      category: "pc components",
      image: "/images/ram3.jpg",
      capacity: "8GB",
      brand: "Corsair",
      price: 82.99,
      countInStock: 0,
      rating: 4.3,
      numReviews: 18,
      description: "high quality product",
    },
    {
      type: "Memory Ram HyperX Fury",
      category: "pc components",
      image: "/images/ram4.jpg",
      capacity: "8GB",
      brand: "Hyperx",
      price: 74.99,
      countInStock: 22,
      rating: 4.5,
      numReviews: 6,
      description: "high quality product",
    },
    {
      type: "Memory Ram Xpg Spectrix",
      category: "pc components",
      image: "/images/ram5.jpg",
      capacity: "8GB",
      brand: "Adata",
      price: 108.99,
      countInStock: 3,
      rating: 4.5,
      numReviews: 22,
      description: "high quality product",
    },
  ],
};

export default data;
