export const CAR_ADD_ITEM = "CAR_ADD_ITEM";
export const CAR_REMOVE_ITEM = "CAR_REMOVE_ITEM";
export const CAR_SAVE_SHOPPING_ADDRESS = "CAR_SAVE_SHOPPING_ADDRESS";
export const CAR_SAVE_PAYMENT_METHOD = "CAR_SAVE_PAYMENT_METHOD";
export const CAR_EMPTY = "CAR_EMPTY";
