const data = {
  products: [
    {
      _id: "1",
      type: "Memory Ram",
      category: "pc components",
      image: "/images/ram1.jpg",
      capacity: "8GB",
      brand: "Corsair",
      price: 172.99,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      type: "Memory Ram",
      category: "pc components",
      image: "/images/ram2.jpg",
      capacity: "8GB",
      brand: "PNY",
      price: 84.99,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      _id: "3",
      type: "Memory Ram",
      category: "pc components",
      image: "/images/ram3.jpg",
      capacity: "8GB",
      brand: "Corsair",
      price: 82.99,
      rating: 4.3,
      numReviews: 18,
      description: "high quality product",
    },
    {
      _id: "4",
      type: "Memory Ram",
      category: "pc components",
      image: "/images/ram4.jpg",
      capacity: "8GB",
      brand: "Hyperx",
      price: 74.99,
      rating: 4.5,
      numReviews: 6,
      description: "high quality product",
    },
    {
      _id: "5",
      type: "Memory Ram",
      category: "pc components",
      image: "/images/ram5.jpg",
      capacity: "8GB",
      brand: "Adata",
      price: 108.99,
      rating: 4.5,
      numReviews: 22,
      description: "high quality product",
    },
  ],
};

export default data;
